### ISSUE TITLE
AttractMode quitting when modify options

### ISSUE THREAD

**Issue by sergiohf** [pcca-matrix/PCCA-Layout#9] opened 2020-06-26 03:40 UTC
Testing the image in windows i am experiencing an abnormal behavior. Every time i enter the display option and change anything, once i leave the option screen, the AttractMode quits and i have to open again.

**Comment by pcca-matrix** [comment] 2020-06-28 12:54
can you please post the log file

**Comment by sergiohf** [comment] 2020-06-29 00:58
Here is the log. The system quit not only when i modify options, but also if i leave and enter the layout again (i have other layouts for my other systems)
[last_run.log](https://github.com/pcca-matrix/PCCA-Layout/files/4843275/last_run.log)

**Comment by pcca-matrix** [comment] 2020-06-29 07:15
cannot reproduce the issue.
can you please post the debug log with attract --loglevel debug 
what other layouts are you using ? maybe an incompatibility between them
does it also crash if you use the pcca layout only?

**Comment by sergiohf** [comment] 2020-06-29 11:01
Sure, i did the loglevel debug. I use a lot of different layouts that i like to test. I was using a modified hyperspin.nut, but i have changed to your layout, and even in that case the system crashed. The system started correctly (main menu pcca), then i entered Arcade, and all ok, the I press right to go to atari system (also pcca), and worked ok, then i came back to arcade, pressing left, ok again, then i pressed esc to return to the main menu, and crashed.  I am posting both and a video of the crashing happening. 
Cant upload the logs here, so they are in this link: [https://mega.nz/file/W4tBCRYD#X2KbmHNFY_sLKSS978-WZ0oVIKDFUHCyQS7irC4dnQE](url) and the video in this link [https://www.youtube.com/watch?v=0oBOedbPN0E](url) When the screen turns black means the the system crashed, but obs didnt record.

**Comment by pcca-matrix** [comment] 2020-06-29 21:25
while reading your logs we can see that you have a problem with your Nvidia GPU Driver.

NvAPI: nvapi64.dll not found

the theme intensely uses opengl shader, yous should update your nvidia gpu driver to get the missing nvapi64.dll file

this should fix the problem.

let me know

**Comment by sergiohf** [comment] 2020-06-30 01:14
Thats weird, my notebook has an intel HD4000 as graphic card, so doesn't make sense this error with an nvidia file. I will try in different machines, since my installation is in an external HD. If something new appears i will tell you.

**Comment by Yaron2019** [comment] 2020-06-30 07:47
Hi sergio! Good to see you here.
I have tried many times reproducing this bug but with no success.
Are you able to reproduce it consistently?

**Comment by pcca-matrix** [comment] 2020-06-30 09:47
Sorry, I thought you had an nvidia card, so it's normal that you are missing the file if you have an intel  hd 4000.

for your gpu it is important to leave it in LOW GPU mode.

Maybe I should lighten the low_gpu_shader again.

**Comment by sergiohf** [comment] 2020-06-30 16:02
> Hi sergio! Good to see you here.
> I have tried many times reproducing this bug but with no success.
> Are you able to reproduce it consistently?

Yes, every single time i try to modify any attractmode settings, when i go back to the pcca theme the system quits. What i have already tried: 
1) Test on other computer (also intel HD graphics), with another version of windows (windows 8)
2) download attract mode again and start a clean installation, only with arcade games,art and themes, i remade the romlists and the only system avaliable is arcade
3) Transfer the installation to my internal hdd
4) set the parameters to low
5) disable everything in the layout
6) download today the layout again and replace all files

Even so, every time the layout needs to be reloaded the system quits. Perhaps its related with this internal graphics card, idk, I will need to try on a system with a different video card.

**Comment by sergiohf** [comment] 2020-06-30 17:10
I could confirm. I tested on an old desktop, and, although it was slow, did not quit when the layout was reloaded.

**Comment by sergiohf** [comment] 2020-06-30 17:16
> Sorry, I thought you had an nvidia card, so it's normal that you are missing the file if you have an intel hd 4000.
> 
> for your gpu it is important to leave it in LOW GPU mode.
> 
> Maybe I should lighten the low_gpu_shader again.

My system runs in an decent speed your layout, the problem is only in the reloading of the layout, i think is a specific intel HD bug.

**Comment by Yaron2019** [comment] 2020-06-30 18:22
You did great - extensive testing is excellent.

**Comment by pcca-matrix** [comment] 2020-08-15 21:13
this shouldn't be a problem anymore, 
I close the issue, if it wasn't fixed, let me know or reopen the issue.

**Closed by pcca-matrix** 2020-08-15 21:13 UTC
